# Generated by Django 4.2.6 on 2024-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, verbose_name='부문')),
                ('stock_code', models.CharField(max_length=10, verbose_name='주식 코드')),
                ('kr_stock_name', models.CharField(max_length=100, verbose_name='회사 이름')),
                ('date_column', models.DateField(verbose_name='날짜')),
                ('closing_price', models.IntegerField(verbose_name='종가')),
            ],
            options={
                'verbose_name': '주식 일간 종가',
                'verbose_name_plural': '주식 일간 종가들',
            },
        ),
    ]
