# Generated by Django 5.0.2 on 2024-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='차트 이름')),
                ('link', models.CharField(max_length=1000, verbose_name='연결 링크')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
            ],
        ),
    ]
