name: Django CI

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web/stock_data_flow/requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
        working-directory: web/stock_data_flow
