name: Django CD

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/yk99902/stock_pipeline
            source myenv/bin/activate
            git pull origin main
            cd web/stock_data_flow
            python3 manage.py collectstatic --noinput
            python3 manage.py migrate
            sudo systemctl daemon-reload  
            sudo systemctl restart gunicorn.service
            sudo systemctl reload nginx
