name: Django CD

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - ".github/workflows/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Deploy Django Application
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@34.64.83.141 << EOF
          set -e
          cd /home/yk99902/stock_pipeline
          git pull origin main
          source myenv/bin/activate
          cd web/stock_data_flow
          python3 manage.py collectstatic --noinput
          python3 manage.py migrate
          sudo systemctl daemon-reload  
          sudo systemctl restart gunicorn.service
          sudo systemctl reload nginx
          EOF
